# permissions for end users to view podrunners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podrunner-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-operator-kube-builder
    app.kubernetes.io/part-of: k8s-operator-kube-builder
    app.kubernetes.io/managed-by: kustomize
  name: podrunner-viewer-role
rules:
- apiGroups:
  - podrunner.nomadxd.io
  resources:
  - podrunners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - podrunner.nomadxd.io
  resources:
  - podrunners/status
  verbs:
  - get
