---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - podrunner.nomadxd.io
  resources:
  - podrunners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podrunner.nomadxd.io
  resources:
  - podrunners/finalizers
  verbs:
  - update
- apiGroups:
  - podrunner.nomadxd.io
  resources:
  - podrunners/status
  verbs:
  - get
  - patch
  - update
