worker_processes  1;
error_log logs/error.log;

events {
    worker_connections 1024;
}
http {
  init_worker_by_lua_block {
    redis = require("resty.redis")
  }
  server {
    listen 8080;
    lua_code_cache on;

    location = /basic_status {
        stub_status;
    }

    location /dbg {
      content_by_lua_block {
        require('resty.repl').start()
      }
    }
    location /ping {
        resolver local=on;
        content_by_lua_block {
            local red = redis:new()
            red:set_timeout(1000) -- 1 second
            ngx.log(ngx.ERR, "correlation-id: ", correlation_id, " before: ")
            local ok, err = red:connect("toxiproxy", 26379)
            if not ok then
                ngx.say("failed to connect: ", err)
                return
            end
            ngx.log(ngx.ERR, "correlation-id: ", correlation_id, "XXXX connected: ")
            local res, err = red:ping()
            if not res then
                ngx.say("failed to ping redis: ", err)
                return
            end
            ngx.log(ngx.ERR, "correlation-id: ", correlation_id, " after: ")
            ngx.say("reused times: ", red:get_reused_times())
            local ok, err = red:set_keepalive(10000, 100) -- 10 seconds, pool size 2
            if not ok then
                ngx.log(ngx.ERR, "correlation-id: ", correlation_id, " failed to set keepalive: ", err)
                return redisResponse, err
            end

            local red = redis:new()
            local start_time = ngx.now()
            ngx.log(ngx.ERR, "correlation-id: ", correlation_id, " Redis connect start time: ", start_time, " seconds")
            local ok, err = red:connect("toxiproxy", 26379)
            local connect_time = ngx.now()
            ngx.log(ngx.ERR, "correlation-id: ", correlation_id, " Redis connect end time: ", connect_time, " seconds")
            if not ok then
                ngx.say("failed to connect: ", err)
                return
            end
            local time_diff = (connect_time - start_time) * 1000
            ngx.log(ngx.ERR, "correlation-id: ", correlation_id, " Redis connect time: ", time_diff, "milliseconds")
            ngx.say("reused times: ", red:get_reused_times())
            local ok, err = red:set_keepalive(10000, 100) -- 10 seconds, pool size 2
            if not ok then
                ngx.log(ngx.ERR, "correlation-id: ", correlation_id, " failed to set keepalive: ", err)
                return redisResponse, err
            end
        }
    }
    location /pong {
        resolver local=on;
        content_by_lua_block {
            local red = redis:new()
            local ok, err = red:connect("toxiproxy", 26379)
            if not ok then
                ngx.say("failed to connect: ", err)
                return
            end
            ngx.say("reused times: ", red:get_reused_times())
            local ok, err = red:set_keepalive(10000, 100) -- 10 seconds, pool size 2
            if not ok then
                ngx.log(ngx.ERR, "correlation-id: ", correlation_id, " failed to set keepalive: ", err)
                return redisResponse, err
            end
        }
    }
  }
}