server {
    listen 80;
    location /foo {
        access_by_lua_block {
            local uri = ngx.var.uri
            local host = ngx.var.host
            local requestUri = ngx.var.request_uri
            local reg = "^(?<subDomain>[^.]+).*";
            local subDomain = ngx.re.match(host, reg);
            local orgDetailsSubdomain =  subDomain['subDomain'];

            ngx.log(ngx.NOTICE, "uri: ", uri, "host: ", host, "requestUri: ", requestUri, "subDomain: ", subDomain, "orgDetailsSubdomain: ", orgDetailsSubdomain)

        }
        proxy_pass http://backend_dev:8080;
    }
}